apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-agent
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-agent
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    provider: gke
    readonly: true
    createNamespace: false
    replicaCount: 1
    metadataStore:
      enabled: true
    envFrom:
      - secretRef:
          name: api-key-secret
      - configMapRef:
          name: cluster-id-config
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

