apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: castai
  namespace: flux-system
spec:
  interval: 1m
  path: ./castai
  targetNamespace: castai-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-source
    namespace: flux-system
  wait: true
  timeout: 2m

