apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/casterchizeni/gitops.git
  ref:
    branch: main

